# -*- coding: utf-8 -*-
"""atari_dqn_member1_fu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fd4EkA--6ahY_fH9HT1WX2TMK11JZRL4

# 🎮 Formative 3 — Deep Q-Learning (Atari Breakout)
**Member 1 — The Architect**

This notebook trains a DQN agent to play Atari Breakout using Stable Baselines 3.
It contains all 10 hyperparameter experiments focused on **Learning Rate** and **Gamma**.

---
**Run order every session:**
1. Cell 1 — Mount Drive
2. Cell 2 — Install packages
3. Cell 3 — Register Atari envs
4. Cell 4 — Verify environment
5. Cell 5 — Imports
6. Then jump to whichever experiment you want to run

## 📦 Step 1 — Mount Google Drive
We mount Google Drive so all trained models are saved there.
This protects your work if Colab disconnects or crashes.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 📥 Step 2 — Install Dependencies
Installs all required packages:
- `ale-py` — Arcade Learning Environment (runs the Atari ROMs)
- `gymnasium[atari]` — Gym wrapper for Atari games
- `stable-baselines3[extra]` — DQN implementation + extras (progress bar, etc.)

> ⚠️ The `ale-py==0.8.1` error is harmless — it installs the latest version which works fine.
"""

!pip install -q ale-py==0.8.1
!pip install -q "gymnasium[atari, accept-rom-license]"
!pip install -q stable-baselines3[extra]

"""## 🕹️ Step 3 — Register Atari Environments
Gymnasium doesn't automatically know about Atari games.
We must manually register them using `ale_py` every session.
The print confirms `ALE/Breakout-v5` is available.
"""

import ale_py
import gymnasium as gym
gym.register_envs(ale_py)
print("Registered envs:", [e for e in gym.envs.registry.keys() if "Breakout" in e])

"""## ✅ Step 4 — Verify Environment
Creates a test environment and checks the observation shape.

Expected output: `(1, 84, 84, 4)` which means:
- `1` — number of parallel environments
- `84 x 84` — pixel dimensions (resized from original 210x160)
- `4` — number of stacked frames (so the agent can see motion)
"""

from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

env = make_atari_env("ALE/Breakout-v5", n_envs=1, seed=42)
env = VecFrameStack(env, n_stack=4)
obs = env.reset()
print("✅ Environment shape:", obs.shape)  # Expect: (1, 84, 84, 4)
env.close()

"""## 🧠 Step 5 — Imports
Loads all the classes we need:
- `DQN` — the Deep Q-Network algorithm
- `make_atari_env` — helper that applies standard Atari preprocessing (grayscale, resize, frame skip)
- `VecFrameStack` — stacks 4 consecutive frames so the agent understands motion
- `EvalCallback` — evaluates the agent every N steps and saves the best model
- `CheckpointCallback` — saves a backup model every N steps (crash protection)
"""

import os
import ale_py
import gymnasium as gym
gym.register_envs(ale_py)

from stable_baselines3 import DQN
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback, CallbackList
import numpy as np

print("✅ All imports loaded")

"""## 🔧 Helper Functions
These two functions are reused by every experiment:

- `run_experiment()` — builds the environments, DQN agent, callbacks, trains, saves the model
- `get_results()` — loads the eval logs and prints the best and final mean reward

You never need to change these — only the config block above each experiment changes.
"""

import os

def run_experiment(exp_name, lr, gamma, batch_size, buffer_size,
                   exploration_frac, exploration_init, exploration_final,
                   total_steps, env_id="ALE/Breakout-v5", policy="CnnPolicy"):
    """
    Runs a full DQN training experiment and saves the model to Google Drive.

    Parameters:
    - exp_name: folder name for this experiment on Drive
    - lr: learning rate — how fast the agent updates its Q-values
    - gamma: discount factor — how much the agent values future rewards
    - batch_size: number of experiences sampled per training update
    - buffer_size: max experiences stored in replay memory
    - exploration_frac: fraction of training over which epsilon decays
    - exploration_init: starting epsilon (1.0 = fully random)
    - exploration_final: ending epsilon (0.01 = 1% random)
    - total_steps: total environment steps to train for
    """

    # Reset working directory (prevents Colab path errors)
    os.chdir("/content")

    drive_path = f"/content/drive/MyDrive/atari-dqn/models/{exp_name}"
    os.makedirs(drive_path, exist_ok=True)

    print(f"\n{'='*55}")
    print(f"🚀 Experiment: {exp_name}")
    print(f"   lr={lr} | gamma={gamma} | batch={batch_size}")
    print(f"   ε_init={exploration_init} | ε_final={exploration_final} | ε_decay={exploration_frac}")
    print(f"   steps={total_steps:,}")
    print(f"{'='*55}\n")

    # --- Create training and evaluation environments ---
    # make_atari_env applies standard preprocessing:
    #   grayscale, resize to 84x84, frame skip of 4
    # VecFrameStack stacks 4 frames so agent perceives motion
    vec_env  = make_atari_env(env_id, n_envs=1, seed=42)
    vec_env  = VecFrameStack(vec_env, n_stack=4)
    eval_env = make_atari_env(env_id, n_envs=1, seed=0)
    eval_env = VecFrameStack(eval_env, n_stack=4)

    # --- Build DQN agent ---
    # CnnPolicy: uses convolutional layers to process pixel input
    # learning_starts: collect this many steps before training begins
    # train_freq=4: update the network every 4 steps
    # target_update_interval: how often to sync target network
    model = DQN(
        policy                   = policy,
        env                      = vec_env,
        learning_rate            = lr,
        buffer_size              = buffer_size,
        learning_starts          = 10_000,
        batch_size               = batch_size,
        gamma                    = gamma,
        train_freq               = 4,
        target_update_interval   = 1000,
        exploration_fraction     = exploration_frac,
        exploration_initial_eps  = exploration_init,
        exploration_final_eps    = exploration_final,
        verbose                  = 1,
        tensorboard_log          = f"{drive_path}/tb_logs/"
    )

    # --- Callbacks ---
    # EvalCallback: runs evaluation episodes every eval_freq steps
    #   and saves the best performing model automatically
    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path = f"{drive_path}/best/",
        log_path             = f"{drive_path}/eval_logs/",
        eval_freq            = 10_000,
        n_eval_episodes      = 5,
        deterministic        = True,
        render               = False,
        verbose              = 1
    )
    # CheckpointCallback: saves a model snapshot every 50k steps
    #   so you don't lose progress if Colab crashes
    checkpoint_callback = CheckpointCallback(
        save_freq   = 50_000,
        save_path   = f"{drive_path}/checkpoints/",
        name_prefix = exp_name,
        verbose     = 1
    )

    # --- Train ---
    model.learn(
        total_timesteps = total_steps,
        callback        = CallbackList([eval_callback, checkpoint_callback]),
        progress_bar    = True
    )

    # --- Save final model ---
    model.save(f"{drive_path}/final_model")
    print(f"\n✅ Training done! Model saved to {drive_path}/final_model.zip")

    vec_env.close()
    eval_env.close()
    return drive_path


def get_results(drive_path, exp_name, lr, gamma, batch_size, total_steps):
    """
    Loads evaluation logs and prints the best and final mean reward.
    Run this immediately after run_experiment() completes.

    - Best mean reward: highest average score across any eval checkpoint
    - Final mean reward: average score at the very last eval checkpoint
    """
    eval_log     = np.load(f"{drive_path}/eval_logs/evaluations.npz", allow_pickle=True)
    mean_rewards = eval_log['results'].mean(axis=1)
    best_reward  = mean_rewards.max()
    final_reward = mean_rewards[-1]

    print(f"\n{'='*55}")
    print(f"📊 Results: {exp_name}")
    print(f"   Best mean reward:  {best_reward:.2f}")
    print(f"   Final mean reward: {final_reward:.2f}")
    print(f"   lr={lr} | gamma={gamma} | batch={batch_size} | steps={total_steps}")
    print(f"{'='*55}")
    return best_reward, final_reward

print("✅ Helper functions ready")

"""---
# 🧪 Experiments

**Member 1 focus:** Learning Rate (`lr`) and Gamma (`γ`)

| # | What changes | Why |
|---|---|---|
| Exp 1 | Baseline (lr=1e-4, γ=0.99) | Reference point for all comparisons |
| Exp 2 | lr=1e-3 (10x higher) | Does faster learning help? |
| Exp 3 | lr=1e-2 (very high) | Is there a point where lr is too high? |
| Exp 4 | lr=5e-5 (lower) | Does slower learning give better stability? |
| Exp 5 | lr=1e-5 (very low) | Too slow to learn in 100k steps? |
| Exp 6 | lr=5e-4 (mid) | Sweet spot between exp1 and exp2? |
| Exp 7 | γ=0.90 (low) | Agent values immediate rewards more |
| Exp 8 | γ=0.95 (medium) | Balance between present and future |
| Exp 9 | γ=0.80 (very low) | Heavily short-term — likely poor |
| Exp 10 | Best config, more steps | Confirm best with longer training |

> ⏱️ **Time guide:** Exp 1 = 150k steps (~1.5h). Exp 2–9 = 100k steps (~60min each). Run 2 per Colab session.

---
## 🔬 Experiment 1 — Baseline
**Config:** `lr=1e-4, gamma=0.99, batch=32, steps=150k`

This is the **default config** from the DQN paper. All other experiments are compared against this.
- `lr=1e-4` is the standard learning rate for DQN on Atari
- `gamma=0.99` means the agent values rewards 99 steps in the future almost as much as immediate ones
- Already completed ✅ — **Best reward: 14.40**
"""

drive_path = run_experiment(
    exp_name         = "exp1_baseline",
    lr               = 1e-4,
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 100_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 150_000
)

get_results(
    drive_path = drive_path,
    exp_name   = "exp1_baseline",
    lr         = 1e-4,
    gamma      = 0.99,
    batch_size = 32,
    total_steps= 150_000
)

"""---
## 🔬 Experiment 2 — High Learning Rate
**Config:** `lr=1e-3, gamma=0.99, batch=32, steps=100k`

Learning rate is **10x higher** than baseline.
- Higher lr = larger weight updates per step = faster learning
- Risk: updates become too large and the Q-values become unstable
- **Watch for:** `ep_rew_mean` rising faster early but possibly collapsing later
"""

drive_path = run_experiment(
    exp_name         = "exp2_lr_high",
    lr               = 1e-3,       # 10x higher than baseline
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 100_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp2_lr_high", 1e-3, 0.99, 32, 100_000)

"""---
## 🔬 Experiment 3 — Very High Learning Rate
**Config:** `lr=1e-2, gamma=0.99, batch=32, steps=100k`

Learning rate pushed to an extreme — **100x higher** than baseline.
- At this level the gradient steps overshoot the optimal Q-values
- The network weights oscillate wildly instead of converging
- **Watch for:** `ep_rew_mean` jumping around with no clear upward trend
"""

drive_path = run_experiment(
    exp_name         = "exp3_lr_very_high",
    lr               = 1e-2,       # 100x higher than baseline
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 100_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp3_lr_very_high", 1e-2, 0.99, 32, 100_000)

"""---
## 🔬 Experiment 4 — Low Learning Rate
**Config:** `lr=5e-5, gamma=0.99, batch=32, steps=100k`

Learning rate is **2x lower** than baseline.
- Smaller updates = more stable training
- But: takes longer to learn meaningful behaviour
- **Watch for:** `ep_rew_mean` rising slowly but steadily — less noise than exp2/exp3
"""

drive_path = run_experiment(
    exp_name         = "exp4_lr_low",
    lr               = 5e-5,       # 2x lower than baseline
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 100_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp4_lr_low", 5e-5, 0.99, 32, 100_000)

"""---
## 🔬 Experiment 5 — Very Low Learning Rate
**Config:** `lr=1e-5, gamma=0.99, batch=32, steps=100k`

Learning rate pushed to an extreme in the other direction — **10x lower** than baseline.
- Updates are so tiny that the agent barely changes its behaviour across 100k steps
- Would need millions of steps to converge
- **Watch for:** `ep_rew_mean` staying almost flat throughout training
"""

drive_path = run_experiment(
    exp_name         = "exp5_lr_very_low",
    lr               = 1e-5,       # 10x lower than baseline
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 100_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp5_lr_very_low", 1e-5, 0.99, 32, 100_000)

"""---
## 🔬 Experiment 6 — Mid Learning Rate
**Config:** `lr=5e-4, gamma=0.99, batch=32, steps=100k`

Learning rate sits **between baseline (1e-4) and high (1e-3)**.
- Often the best performing config — fast enough to learn but stable
- This is likely to beat the baseline on fewer steps
- **Watch for:** faster reward growth than exp1 with less instability than exp2
"""

drive_path = run_experiment(
    exp_name         = "exp6_lr_mid",
    lr               = 5e-4,       # between baseline and high
    gamma            = 0.99,
    batch_size       = 32,
    buffer_size      = 50_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp6_lr_mid", 5e-4, 0.99, 32, 100_000)

"""---
## 🔬 Experiment 7 — Low Gamma
**Config:** `lr=1e-4, gamma=0.90, batch=32, steps=100k`

Gamma controls how much the agent **discounts future rewards**.
- `gamma=0.90` means a reward 10 steps away is worth only 0.90^10 = 35% of its face value
- The agent becomes more short-sighted — focuses on immediate points
- For Breakout this can hurt because breaking high bricks requires planning ahead
- **Watch for:** agent may score okay early but stop improving at a lower ceiling
"""

drive_path = run_experiment(
    exp_name         = "exp7_gamma_low",
    lr               = 1e-4,
    gamma            = 0.90,       # more short-term focused
    batch_size       = 32,
    buffer_size      = 50_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp7_gamma_low", 1e-4, 0.90, 32, 100_000)

"""---
## 🔬 Experiment 8 — Medium Gamma
**Config:** `lr=1e-4, gamma=0.95, batch=32, steps=100k`

Gamma sits **between low (0.90) and baseline (0.99)**.
- `gamma=0.95` means a reward 10 steps away is worth 0.95^10 = 60% of face value
- Often a sweet spot — balances short-term scoring with planning ahead
- **Watch for:** comparable to or slightly below baseline — good stability
"""

drive_path = run_experiment(
    exp_name         = "exp8_gamma_mid",
    lr               = 1e-4,
    gamma            = 0.95,       # between low and baseline
    batch_size       = 32,
    buffer_size      = 50_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp8_gamma_mid", 1e-4, 0.95, 32, 100_000)

"""---
## 🔬 Experiment 9 — Very Low Gamma
**Config:** `lr=1e-4, gamma=0.80, batch=32, steps=100k`

Gamma pushed to an extreme — agent is **heavily short-term**.
- `gamma=0.80` means a reward 10 steps away is worth only 0.80^10 = 10% of face value
- The agent essentially ignores anything more than a few steps ahead
- For Breakout (which requires multi-step planning) this should perform poorly
- **Watch for:** low `ep_rew_mean` — agent reacts to immediate rewards only
"""

drive_path = run_experiment(
    exp_name         = "exp9_gamma_very_low",
    lr               = 1e-4,
    gamma            = 0.80,       # heavily short-term
    batch_size       = 32,
    buffer_size      = 50_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 100_000
)

get_results(drive_path, "exp9_gamma_very_low", 1e-4, 0.80, 32, 100_000)

"""---
## 🔬 Experiment 10 — Best Config (Longer Run) ⭐
**Config:** Use the `lr` and `gamma` that gave the highest reward in exp 2–9, with 200k steps.

After reviewing all results:
- Pick the experiment with the **highest Best mean reward**
- Use those `lr` and `gamma` values below
- Run for **200k steps** to confirm it truly is the best config with more training time

> ✏️ **Update the config below before running** — replace the lr and gamma with your actual best values from exp 2–9.
"""

# ── UPDATE THESE with your best values from exp 2-9 ──────────
BEST_LR    = 5e-4   # ← replace with your best lr
BEST_GAMMA = 0.99   # ← replace with your best gamma
# ─────────────────────────────────────────────────────────────

drive_path = run_experiment(
    exp_name         = "exp10_best_config",
    lr               = BEST_LR,
    gamma            = BEST_GAMMA,
    batch_size       = 32,
    buffer_size      = 50_000,
    exploration_frac = 0.1,
    exploration_init = 1.0,
    exploration_final= 0.01,
    total_steps      = 200_000    # longer run to confirm best config
)

get_results(drive_path, "exp10_best_config", BEST_LR, BEST_GAMMA, 32, 200_000)

"""---
## 📊 Results Summary
Run this cell after all experiments are complete to print a full comparison table.
This is what you fill into the assignment hyperparameter table.
"""

experiments = [
    {"name": "exp1_baseline",      "lr": 1e-4,  "gamma": 0.99, "batch": 32, "steps": 150_000},
    {"name": "exp2_lr_high",       "lr": 1e-3,  "gamma": 0.99, "batch": 32, "steps": 100_000},
    {"name": "exp3_lr_very_high",  "lr": 1e-2,  "gamma": 0.99, "batch": 32, "steps": 100_000},
    {"name": "exp4_lr_low",        "lr": 5e-5,  "gamma": 0.99, "batch": 32, "steps": 100_000},
    {"name": "exp5_lr_very_low",   "lr": 1e-5,  "gamma": 0.99, "batch": 32, "steps": 100_000},
    {"name": "exp6_lr_mid",        "lr": 5e-4,  "gamma": 0.99, "batch": 32, "steps": 100_000},
    {"name": "exp7_gamma_low",     "lr": 1e-4,  "gamma": 0.90, "batch": 32, "steps": 100_000},
    {"name": "exp8_gamma_mid",     "lr": 1e-4,  "gamma": 0.95, "batch": 32, "steps": 100_000},
    {"name": "exp9_gamma_very_low","lr": 1e-4,  "gamma": 0.80, "batch": 32, "steps": 100_000},
    {"name": "exp10_best_config",  "lr": BEST_LR, "gamma": BEST_GAMMA, "batch": 32, "steps": 200_000},
]

print(f"{'#':<4} {'Experiment':<25} {'lr':<8} {'gamma':<7} {'steps':<8} {'Best Reward':<13} {'Final Reward'}")
print("-" * 80)

for i, exp in enumerate(experiments, 1):
    path = f"/content/drive/MyDrive/atari-dqn/models/{exp['name']}/eval_logs/evaluations.npz"
    try:
        log          = np.load(path, allow_pickle=True)
        mean_rewards = log['results'].mean(axis=1)
        best         = mean_rewards.max()
        final        = mean_rewards[-1]
        print(f"{i:<4} {exp['name']:<25} {exp['lr']:<8} {exp['gamma']:<7} {exp['steps']:<8} {best:<13.2f} {final:.2f}")
    except FileNotFoundError:
        print(f"{i:<4} {exp['name']:<25} {exp['lr']:<8} {exp['gamma']:<7} {exp['steps']:<8} {'Not run yet':<13} -")

"""---
## 💾 Push Best train.py to GitHub
After all experiments, save the best config as `train.py` and push to the repo.

> ✏️ Update `BEST_LR` and `BEST_GAMMA` with your actual best values before running.
"""

import os
os.chdir("/content")

# ── Fill in your details ──────────────────────────────────────
GITHUB_USERNAME = "Sng43"
GITHUB_TOKEN    = "paste_your_token_here"  # ← new token from GitHub
REPO_NAME       = "atari-dqn"
# ─────────────────────────────────────────────────────────────

# Write train.py with the best experiment config
train_script = f'''import os
import ale_py
import gymnasium as gym
gym.register_envs(ale_py)

from stable_baselines3 import DQN
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback, CallbackList

# ── BEST CONFIG (from exp10) ─────────────────────────────────
EXP_NAME          = "exp10_best_config"
LEARNING_RATE     = {BEST_LR}
GAMMA             = {BEST_GAMMA}
BATCH_SIZE        = 32
BUFFER_SIZE       = 100_000
EXPLORATION_FRAC  = 0.1
EXPLORATION_INIT  = 1.0
EXPLORATION_FINAL = 0.01
TOTAL_STEPS       = 200_000
# ─────────────────────────────────────────────────────────────

ENV_ID     = "ALE/Breakout-v5"
POLICY     = "CnnPolicy"
DRIVE_PATH = f"/content/drive/MyDrive/atari-dqn/models/{{EXP_NAME}}"
os.makedirs(DRIVE_PATH, exist_ok=True)

vec_env  = make_atari_env(ENV_ID, n_envs=1, seed=42)
vec_env  = VecFrameStack(vec_env, n_stack=4)
eval_env = make_atari_env(ENV_ID, n_envs=1, seed=0)
eval_env = VecFrameStack(eval_env, n_stack=4)

model = DQN(
    policy                   = POLICY,
    env                      = vec_env,
    learning_rate            = LEARNING_RATE,
    buffer_size              = BUFFER_SIZE,
    learning_starts          = 10_000,
    batch_size               = BATCH_SIZE,
    gamma                    = GAMMA,
    train_freq               = 4,
    target_update_interval   = 1000,
    exploration_fraction     = EXPLORATION_FRAC,
    exploration_initial_eps  = EXPLORATION_INIT,
    exploration_final_eps    = EXPLORATION_FINAL,
    verbose                  = 1,
    tensorboard_log          = f"{{DRIVE_PATH}}/tb_logs/"
)

eval_callback = EvalCallback(
    eval_env,
    best_model_save_path = f"{{DRIVE_PATH}}/best/",
    log_path             = f"{{DRIVE_PATH}}/eval_logs/",
    eval_freq            = 10_000,
    n_eval_episodes      = 5,
    deterministic        = True,
    render               = False,
    verbose              = 1
)

checkpoint_callback = CheckpointCallback(
    save_freq   = 50_000,
    save_path   = f"{{DRIVE_PATH}}/checkpoints/",
    name_prefix = EXP_NAME,
    verbose     = 1
)

print(f"Training {{EXP_NAME}} | lr={{LEARNING_RATE}} | gamma={{GAMMA}} | steps={{TOTAL_STEPS}}")
model.learn(
    total_timesteps = TOTAL_STEPS,
    callback        = CallbackList([eval_callback, checkpoint_callback]),
    progress_bar    = True
)

model.save(f"{{DRIVE_PATH}}/final_model")
print(f"Done! Saved to {{DRIVE_PATH}}/final_model.zip")
vec_env.close()
eval_env.close()
'''

with open("/content/drive/MyDrive/atari-dqn/train.py", "w") as f:
    f.write(train_script)
print("✅ train.py saved to Drive")